<?php
namespace App\Http\Resources;

use App\Models\Keluarga;
use Illuminate\Http\Resources\Json\JsonResource;

class PendudukResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'deleted_at' => $this->deleted_at,
            'nik' => $this->nik,
            'chip_ektp' => $this->ktp_el,
            'nama' => $this->nama ?? null,
            'tgl_lahir' => $this->tanggallahir,
            'tempat_lahir' => $this->tempatlahir,
            'jk' => $this->jenisKelamin->nama ?? null,
            'alamat_sekarang' => $this->alamat_sekarang,
            'agama' => $this->agama->nama ?? null,
            'pendidikan' => $this->pendidikanKk->nama ?? null,
            'pekerjaan' => $this->pekerjaan->nama ?? null,
            'status_kawin' => $this->statusKawin->nama ?? null,
            'status_penduduk' => $this->status_penduduk,
            'kewarganegaraan' => $this->kewarganegaraan->nama ?? null,
            'anak_ke' => $this->kelahiran_anak_ke,
            'golongan_darah' => $this->golonganDarah->nama ?? null,
            'status_dalam_keluarga' => $this->status_dalam_keluarga,
            'no_paspor' => $this->dokumen_pasport,
            'suku' => $this->suku,
            'potensi_diri' => $this->potensi_diri,
            'no_hp' => $this->telepon,
            'nik_ayah' => $this->ayah_nik,
            'nik_ibu' => $this->ibu_nik,
            'nama_ayah' => $this->nama_ayah,
            'nama_ibu' => $this->nama_ibu,
            'tgl_exp_paspor' => $this->tanggal_akhir_paspor,
            'akta_lahir' => $this->akta_lahir,
            'akta_kawin' => $this->akta_perkawinan,
            'tgl_kawin' => $this->tanggalperkawinan,
            'akta_cerai' => $this->akta_perkawinan,
            'tgl_cerai' => $this->tanggalperceraian,
            'kelainan_fisik' => $this->kelainan_fisik,
            'cacat' => $this->cacat->nama ?? null,
            'foto' => $this->foto,
            'pass_field' => $this->pass_field,
            'status_covid' => $this->status_covid,
            'status_vaksin' => $this->status_vaksin,
            'status_stunting' => $this->status_stunting,
            'created_by' => $this->created_by,
            'updated_by' => $this->updated_by,
            'deleted_by' => $this->deleted_by,
            'keluaga' => KeluargaResource::collection($this->whenLoaded('keluarga')),
            // 'id_kk' => $this->name,
            // 'kk_level' => $this->name,
            // 'id_rtm' => $this->name,
            // 'rtm_level' => $this->name,
            // 'dokumen_kitas' => $this->name,
            // 'id_cluster' => $this->name,
            // 'status' => $this->name,
            // 'alamat_sebelumnya' => $this->alamat_sebelumnya,
            // 'status_dasar' => $this->name,
            // 'hamil' => $this->hamil,
            // 'sakit_menahun_id' => $this->name,
            // 'cara_kb_id' => $this->name,
            // 'no_kk_sebelumnya' => $this->no_kk_sebelumnya,
            // 'status_rekam' => $this->status_rekam,
            // 'waktu_lahir' => $this->waktu_lahir,
            // 'tempat_dilahirkan' => $this->tempat_dilahirkan,
            // 'jenis_kelahiran' => $this->jenis_kelahiran,
            // 'penolong_kelahiran' => $this->penolong_kelahiran,
            // 'berat_lahir' => $this->berat_lahir,
            // 'panjang_lahir' => $this->panjang_lahir,
            // 'tag_id_card' => $this->tag_id_card,
            // 'id_asuransi' => $this->id_asuransi,
            // 'no_asuransi' => $this->no_asuransi,
            // 'email' => $this->email,
        ];
    }
}