name: Lumen Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run Migration
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --seed
    - name: Generate key
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan key:generate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull update repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_ROOT }}
          key: ${{ secrets.SSH_PRIVATE_KEY_ROOT }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              cd ${{ secrets.DIR_OPENSID_API }}
              git pull
      - name: Run Composer Install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_DEPLOY }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              cd ${{ secrets.DIR_OPENSID_API }}
              php7.4 /usr/local/bin/composer install
      - name: Generate the Docs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_ROOT }}
          key: ${{ secrets.SSH_PRIVATE_KEY_ROOT }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              cd ${{ secrets.DIR_OPENSID_API }}
              php7.4 artisan scribe:generate
